-- MySQL Script generated by MySQL Workbench
-- 06/27/19 00:16:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema beeCommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema beeCommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `beeCommerce` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `beeCommerce` ;

-- -----------------------------------------------------
-- Table `beeCommerce`.`apiario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`apiario` (
  `codApia` INT AUTO_INCREMENT,
  `tamanhoApia` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`codApia`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`endereco` (
  `codEnde` INT AUTO_INCREMENT,
  `bairroEnde` VARCHAR(100) NULL DEFAULT NULL,
  `cepEnde` VARCHAR(8) NULL DEFAULT NULL,
  `cidadeEnde` VARCHAR(100) NULL DEFAULT NULL,
  `ruaEnde` VARCHAR(200) NULL DEFAULT NULL,
  `ufEnde` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`codEnde`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`logradouro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`logradouro` (
  `codLogr` INT AUTO_INCREMENT,
  `complementoLogr` VARCHAR(50) NULL DEFAULT NULL,
  `enderecoLogrFK` INT NULL DEFAULT NULL,
  `numeroLogr` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codLogr`),
  INDEX `fk_{2493027F-EFE8-4377-8413-07F8C074397A}` (`enderecoLogrFK` ASC),
  CONSTRAINT `fk_{2493027F-EFE8-4377-8413-07F8C074397A}`
    FOREIGN KEY (`enderecoLogrFK`)
    REFERENCES `beeCommerce`.`endereco` (`codEnde`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`apiario_has_logradouro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`apiario_has_logradouro` (
  `codAhsL` INT AUTO_INCREMENT,
  `apiarioAhsLFK` INT,
  `logradouroAhsLFK` INT,
  PRIMARY KEY (`codAhsL`),
  INDEX `fk_{E4992805-20B7-4495-AED5-D21C678945E6}` (`apiarioAhsLFK` ASC),
  INDEX `fk_{F7EB27D2-175C-4962-B444-6416EB9F43B4}` (`logradouroAhsLFK` ASC),
  CONSTRAINT `fk_{E4992805-20B7-4495-AED5-D21C678945E6}`
    FOREIGN KEY (`apiarioAhsLFK`)
    REFERENCES `beeCommerce`.`apiario` (`codApia`),
  CONSTRAINT `fk_{F7EB27D2-175C-4962-B444-6416EB9F43B4}`
    FOREIGN KEY (`logradouroAhsLFK`)
    REFERENCES `beeCommerce`.`logradouro` (`codLogr`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`cadastro` (
  `codCada` INT AUTO_INCREMENT,
  `nomeCada` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`codCada`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`cliente` (
  `codCli` INT,
  `nomeCli` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`codCli`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`situacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`situacao` (
  `codSitu` INT AUTO_INCREMENT,
  `nomeSitu` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`codSitu`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`pessoa` (
  `codPess` INT AUTO_INCREMENT,
  `logradouroPessFK` INT,
  `nomePess` VARCHAR(100) NULL DEFAULT NULL,
  `situacaoPessFK` INT,
  `usuarioPessFK` INT,
  PRIMARY KEY (`codPess`),
  INDEX `fk_{818A0A12-DE61-4DE2-B28C-E26930FC485E}` (`logradouroPessFK` ASC),
  INDEX `fk_{B717247C-3443-4378-92AA-16708020A4D1}` (`situacaoPessFK` ASC),
  CONSTRAINT `fk_{818A0A12-DE61-4DE2-B28C-E26930FC485E}`
    FOREIGN KEY (`logradouroPessFK`)
    REFERENCES `beeCommerce`.`logradouro` (`codLogr`),
  CONSTRAINT `fk_{B717247C-3443-4378-92AA-16708020A4D1}`
    FOREIGN KEY (`situacaoPessFK`)
    REFERENCES `beeCommerce`.`situacao` (`codSitu`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`cliente_has_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`cliente_has_pessoa` (
  `codChsP` INT AUTO_INCREMENT,
  `clienteChsPFK` INT,
  `pessoaChsPFK` INT,
  PRIMARY KEY (`codChsP`),
  INDEX `fk_{B0D8B7C1-2461-4C7B-A06E-1FD0CF2A436F}` (`pessoaChsPFK` ASC),
  INDEX `fk_{00D48B21-FF51-4BB2-99C9-4EED9EEA490A}` (`clienteChsPFK` ASC),
  CONSTRAINT `fk_{B0D8B7C1-2461-4C7B-A06E-1FD0CF2A436F}`
    FOREIGN KEY (`pessoaChsPFK`)
    REFERENCES `beeCommerce`.`pessoa` (`codPess`),
  CONSTRAINT `fk_{00D48B21-FF51-4BB2-99C9-4EED9EEA490A}`
    FOREIGN KEY (`clienteChsPFK`)
    REFERENCES `beeCommerce`.`cliente` (`codCli`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`comeia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`comeia` (
  `codCome` INT AUTO_INCREMENT,
  `apiarioCome` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codCome`),
  INDEX `fk_{2E66A490-BF2E-49BD-AED0-623893C46CA1}` (`apiarioCome` ASC),
  CONSTRAINT `fk_{2E66A490-BF2E-49BD-AED0-623893C46CA1}`
    FOREIGN KEY (`apiarioCome`)
    REFERENCES `beeCommerce`.`apiario` (`codApia`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`contato` (
  `codCont` INT AUTO_INCREMENT,
  `pessoaCont` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codCont`),
  INDEX `fk_{BDF8408E-DD84-4F2A-BFCB-29079E2CC4CA}` (`pessoaCont` ASC),
  CONSTRAINT `fk_{BDF8408E-DD84-4F2A-BFCB-29079E2CC4CA}`
    FOREIGN KEY (`pessoaCont`)
    REFERENCES `beeCommerce`.`pessoa` (`codPess`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`email` (
  `codEmai` INT AUTO_INCREMENT,
  `contatoEmaiFK` INT,
  `nomeEmai` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`codEmai`),
  INDEX `fk_{C9F49BA2-3535-4408-9F5A-A663E2A02AFD}` (`contatoEmaiFK` ASC),
  CONSTRAINT `fk_{C9F49BA2-3535-4408-9F5A-A663E2A02AFD}`
    FOREIGN KEY (`contatoEmaiFK`)
    REFERENCES `beeCommerce`.`contato` (`codCont`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`funcionario` (
  `codFunc` INT AUTO_INCREMENT,
  `apiarioFuncFK` INT,
  `pisFunc` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`codFunc`),
  INDEX `fk_{FE57CE49-E467-49AC-86FD-E592F9C2B694}` (`apiarioFuncFK` ASC),
  CONSTRAINT `fk_{FE57CE49-E467-49AC-86FD-E592F9C2B694}`
    FOREIGN KEY (`apiarioFuncFK`)
    REFERENCES `beeCommerce`.`apiario` (`codApia`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`funcionario_has_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`funcionario_has_pessoa` (
  `codFhsP` INT AUTO_INCREMENT,
  `funcionarioFhsPFK` INT,
  `pessoaFhsPFK` INT,
  PRIMARY KEY (`codFhsP`),
  INDEX `fk_{8406CED5-E61C-4D4E-9CBD-F8B16226BD4C}` (`funcionarioFhsPFK` ASC),
  INDEX `fk_{27A34F99-989A-4451-84E6-F359BC859F8C}` (`pessoaFhsPFK` ASC),
  CONSTRAINT `fk_{8406CED5-E61C-4D4E-9CBD-F8B16226BD4C}`
    FOREIGN KEY (`funcionarioFhsPFK`)
    REFERENCES `beeCommerce`.`funcionario` (`codFunc`),
  CONSTRAINT `fk_{27A34F99-989A-4451-84E6-F359BC859F8C}`
    FOREIGN KEY (`pessoaFhsPFK`)
    REFERENCES `beeCommerce`.`pessoa` (`codPess`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`produto` (
  `codProd` INT AUTO_INCREMENT,
  `nomeProd` VARCHAR(200) NULL DEFAULT NULL,
  `quantidadeProd` FLOAT NULL DEFAULT NULL,
  `valorProd` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`codProd`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`pedido` (
  `codPedi` INT AUTO_INCREMENT,
  `clientePediFK` INT,
  `dataPedi` DATE NULL DEFAULT NULL,
  `destinoPediFK` INT,
  `valorVendaPedi` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`codPedi`),
  INDEX `fk_{EAA95AC5-DB53-4E08-A849-64C5B79664EB}` (`clientePediFK` ASC),
  INDEX `fk_{42C1A89A-A351-441B-85FE-F57321FF165A}` (`destinoPediFK` ASC),
  CONSTRAINT `fk_{EAA95AC5-DB53-4E08-A849-64C5B79664EB}`
    FOREIGN KEY (`clientePediFK`)
    REFERENCES `beeCommerce`.`cliente` (`codCli`),
  CONSTRAINT `fk_{42C1A89A-A351-441B-85FE-F57321FF165A}`
    FOREIGN KEY (`destinoPediFK`)
    REFERENCES `beeCommerce`.`logradouro` (`codLogr`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`itemPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`itemPedido` (
  `codItPe` INT AUTO_INCREMENT,
  `produtoItPeFK` INT,
  `pedidoItPeFK` INT,
  `quantidadeItPe` INT NULL DEFAULT NULL,
  `valorItPe` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`codItPe`),
  INDEX `fk_{A5CFDA0D-8BFB-4ECF-85BD-5334D57CB714}` (`produtoItPeFK` ASC),
  INDEX `fk_{F8556606-09B1-47A4-A8C8-8115A93C6DBE}` (`pedidoItPeFK` ASC),
  CONSTRAINT `fk_{A5CFDA0D-8BFB-4ECF-85BD-5334D57CB714}`
    FOREIGN KEY (`produtoItPeFK`)
    REFERENCES `beeCommerce`.`produto` (`codProd`),
  CONSTRAINT `fk_{F8556606-09B1-47A4-A8C8-8115A93C6DBE}`
    FOREIGN KEY (`pedidoItPeFK`)
    REFERENCES `beeCommerce`.`pedido` (`codPedi`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`lote` (
  `codLote` INT AUTO_INCREMENT,
  `comeiaLoteFK` INT,
  `dataProducaoLote` DATE NULL DEFAULT NULL,
  `produtoLoteFK` INT,
  `qualidadeLote` CHAR NULL DEFAULT NULL,
  `quantidadeLote` FLOAT NULL DEFAULT NULL,
  `validadeLote` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`codLote`),
  INDEX `fk_{521EF78C-6F79-4BDA-82C1-6ED139B2F1C8}` (`comeiaLoteFK` ASC),
  INDEX `fk_{46879D11-0EBA-45D1-B281-F70D38435620}` (`produtoLoteFK` ASC),
  CONSTRAINT `fk_{521EF78C-6F79-4BDA-82C1-6ED139B2F1C8}`
    FOREIGN KEY (`comeiaLoteFK`)
    REFERENCES `beeCommerce`.`comeia` (`codCome`),
  CONSTRAINT `fk_{46879D11-0EBA-45D1-B281-F70D38435620}`
    FOREIGN KEY (`produtoLoteFK`)
    REFERENCES `beeCommerce`.`produto` (`codProd`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`permissao` (
  `codPerm` INT AUTO_INCREMENT,
  `nomePerm` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`codPerm`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`permissao_has_cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`permissao_has_cadastro` (
  `codPerHsCad` INT AUTO_INCREMENT,
  `cadastroPhsCFK` INT,
  `permissaoPhsCFK` INT,
  `criarPhsC` TINYINT NULL DEFAULT NULL,
  `consultarPhsC` TINYINT NULL DEFAULT NULL,
  `alterarPhsC` TINYINT NULL DEFAULT NULL,
  `apagarPhsC` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`codPerHsCad`),
  INDEX `fk_{A1C1A283-59E5-4304-8FFB-83A128A605D1}` (`permissaoPhsCFK` ASC),
  INDEX `fk_{17AA81B1-77C1-4F26-A40C-3CCD6C6DB95B}` (`cadastroPhsCFK` ASC),
  CONSTRAINT `fk_{A1C1A283-59E5-4304-8FFB-83A128A605D1}`
    FOREIGN KEY (`permissaoPhsCFK`)
    REFERENCES `beeCommerce`.`permissao` (`codPerm`),
  CONSTRAINT `fk_{17AA81B1-77C1-4F26-A40C-3CCD6C6DB95B}`
    FOREIGN KEY (`cadastroPhsCFK`)
    REFERENCES `beeCommerce`.`cadastro` (`codCada`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`usuario` (
  `codUsua` INT AUTO_INCREMENT,
  `nomeUsua` VARCHAR(20) NULL DEFAULT NULL,
  `permissaoUsuaFK` INT,
  `pessoaUsuaFK` INT,
  `senhaUsua` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`codUsua`),
  INDEX `fk_{2A2CF7B1-BEA8-4FDD-966F-54A3AE0FD98C}` (`permissaoUsuaFK` ASC),
  INDEX `fk_{D7B1E3A6-76C3-4768-9F57-717789C0AA2E}` (`pessoaUsuaFK` ASC),
  CONSTRAINT `fk_{2A2CF7B1-BEA8-4FDD-966F-54A3AE0FD98C}`
    FOREIGN KEY (`permissaoUsuaFK`)
    REFERENCES `beeCommerce`.`permissao` (`codPerm`),
  CONSTRAINT `fk_{D7B1E3A6-76C3-4768-9F57-717789C0AA2E}`
    FOREIGN KEY (`pessoaUsuaFK`)
    REFERENCES `beeCommerce`.`pessoa` (`codPess`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`telefone` (
  `codTele` INT AUTO_INCREMENT,
  `numeroTele` VARCHAR(11) NULL DEFAULT NULL,
  `contatoTeleFK` INT,
  PRIMARY KEY (`codTele`),
  INDEX `fk_{6EFC2CAF-1283-4270-A0C9-33643DFA18DA}` (`contatoTeleFK` ASC),
  CONSTRAINT `fk_{6EFC2CAF-1283-4270-A0C9-33643DFA18DA}`
    FOREIGN KEY (`contatoTeleFK`)
    REFERENCES `beeCommerce`.`contato` (`codCont`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`tipoPagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`tipoPagamento` (
  `codTiPa` INT AUTO_INCREMENT,
  `nomeTiPa` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`codTiPa`));


-- -----------------------------------------------------
-- Table `beeCommerce`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeCommerce`.`venda` (
  `codVend` INT AUTO_INCREMENT,
  `dataVend` DATE NULL DEFAULT NULL,
  `funcionarioVendFK` INT,
  `pedidoVendFK` INT,
  `qtdParcelas` INT NULL DEFAULT NULL,
  `tipoPagamentoVendFK` INT,
  PRIMARY KEY (`codVend`),
  INDEX `fk_{4D8AF8C0-141D-4F37-8919-BE0565253A94}` (`funcionarioVendFK` ASC),
  INDEX `fk_{5031855A-055E-48F4-9502-D8527494C15C}` (`pedidoVendFK` ASC),
  INDEX `fk_{6836D88D-1200-4ADA-BAA5-4991C59DB4FD}` (`tipoPagamentoVendFK` ASC),
  CONSTRAINT `fk_{4D8AF8C0-141D-4F37-8919-BE0565253A94}`
    FOREIGN KEY (`funcionarioVendFK`)
    REFERENCES `beeCommerce`.`funcionario` (`codFunc`),
  CONSTRAINT `fk_{5031855A-055E-48F4-9502-D8527494C15C}`
    FOREIGN KEY (`pedidoVendFK`)
    REFERENCES `beeCommerce`.`pedido` (`codPedi`),
  CONSTRAINT `fk_{6836D88D-1200-4ADA-BAA5-4991C59DB4FD}`
    FOREIGN KEY (`tipoPagamentoVendFK`)
    REFERENCES `beeCommerce`.`tipoPagamento` (`codTiPa`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
